### ISSUE TITLE
Fixer is incorrectly handling rest properties

### ISSUE THREAD

**Issue by briandastous** [mthadley/eslint-plugin-sort-destructure-keys#11]
Thanks for creating this useful plugin. I noticed that the fixer is incorrectly sorting rest properties to the beginning of the object literal, e.g., `{a, ...rest}` is changed to `{...rest, a}`.

I have a fix for this locally. I've never submitted a PR before on Github, but I'll try to submit one for this soon.

**Comment by mthadley** [comment]
Thanks for reporting this! Released as `v1.3.1`.
