### ISSUE TITLE
Already exists

### ISSUE THREAD

**Issue by Manu1400** [mthadley/eslint-plugin-sort-destructure-keys#2]
https://github.com/wyze/eslint-plugin-wyze/blob/master/docs/rules/sort-destructuring-keys.md

**Comment by johnathanludwig** [comment]
This plugin handles the output better:

![screen shot 2018-12-11 at 3 30 19 pm](https://user-images.githubusercontent.com/1262078/49828409-cee79400-fd59-11e8-893f-2f6ba3d263cb.png)

The wyze plugin likes to highlight all of the keys:

![screen shot 2018-12-11 at 3 28 56 pm](https://user-images.githubusercontent.com/1262078/49828430-e4f55480-fd59-11e8-8121-3c912098c420.png)

**Comment by mthadley** [comment]
Closing since there doesn't seem to be any further discussion here. Thanks!
