### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by bfintal** [mthadley/eslint-plugin-sort-destructure-keys#3]
> TypeError: Cannot read property 'toString' of undefined
> node_modules/eslint-plugin-sort-destructure-keys/lib/rules/sort-destructure-keys.js:9:22

```js
function getNodeName(node) {
    return typeof node.name === 'undefined'
        ? node.value.toString()
        : node.name;
}
```

**Comment by mthadley** [comment]
@bfintal Do you have any more context for this particular error? The code being linted that threw this error, or maybe [which parser was used?](https://eslint.org/docs/user-guide/configuring#specifying-parser)

**Comment by mthadley** [comment]
If any further information is found, feel free to re-open. Otherwise, I'm going to close this. Thanks!
