### ISSUE TITLE
Update package.json to support eslint 5

### ISSUE THREAD

**Issue by RatchapongT** [mthadley/eslint-plugin-sort-destructure-keys#4]
Thank you for this plugin!
Can you please add eslint 5 as peer dependency. 

Right now my project is warning
`eslint-plugin-sort-destructure-keys@1.1.0 requires a peer of eslint@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.`

It seems this plugin is working fine with eslint 5. Thank you!

**Comment by mthadley** [comment]
Thanks, @RatchapongT! This should be fixed in `1.2.0`, which is now published.
