### ISSUE TITLE
Fix eslint 7 incompatibility warning

### ISSUE THREAD

**Issue by dsernst** [mthadley/eslint-plugin-sort-destructure-keys#52]
Getting this warning whenever I add/remove any packages (from `yarn`):

<img width="527" alt="image" src="https://user-images.githubusercontent.com/6340841/85086912-db3f7f00-b190-11ea-94bb-ad0cb59d2f37.png">

I've been using `eslint: 7.2.0` without any compatibility issues.

Similar to https://github.com/mthadley/eslint-plugin-sort-destructure-keys/issues/4

**Comment by mthadley** [comment]
Fix published in [`1.3.5`](https://www.npmjs.com/package/eslint-plugin-sort-destructure-keys/v/1.3.5).
