### ISSUE TITLE
Support for destructure of arguments?

### ISSUE THREAD

**Issue by leepowellcouk** [mthadley/eslint-plugin-sort-destructure-keys#8]
Does this plugin support for destructuring of arguments?
```
const App = ({ bProp, aProp, }) => void;
```

**Comment by mthadley** [comment]
It does. There's also a test case for object patterns in function arguments:

https://github.com/mthadley/eslint-plugin-sort-destructure-keys/blob/master/tests/lib/rules/sort-destructure-keys.js#L115

**Comment by mthadley** [comment]
Closing since there doesn't seem to be any further questions or discussion. Thanks!
